### ISSUE TITLE
إعادة تسمية مجلد poetry إلى ashaar

### ISSUE THREAD

**Issue by AliOsm** [ARBML/tnqeeb#14]
يجب الأخذ بعين الإعتبار أن اسم المجلد `poetry` منتشر في الشفرة البرمجية.  
إذا أمكن إعادة تسمية المجلد واستخراجه من الشفرة البرمجية بحيث يتم ذكره في مكان واحد فقط سيكون هذا أفضل بكثير.

**Comment by zaidalyafeai** [comment]
هل يفضل أن نحذف المجلد بالكامل ، بحيث أن الواجهة الرئيسية للشفرة تحتوي data, src, test ؟

**Comment by AliOsm** [comment]
> هل يفضل أن نحذف المجلد بالكامل ، بحيث أن الواجهة الرئيسية للشفرة تحتوي data, src, test ؟

الأفضل أن يبقى `ashaar` موجود، لأن مستقبلًا سنقوم بإضافة أشياء غيره.
