### ISSUE TITLE
مشكلة في استخراج الصفحات المتتالية بعد الصفحة الرئيسة

### ISSUE THREAD

**Issue by MagedSaeed** [ARBML/tnqeeb#2]
لدينا مشكلة هنا وهي أنه في الشفرة البرمجية التأسيسية (base)، المعالج (processor) يعيد الصفحات التالية كروابط، لينشئ بعدها المستخرج spider طلبا بناء على كل رابط.

برغم كون هذا الشيء منطقي، إلا أنه ليس كل الصفحات المتتالية يتم طلبها عن طريق رابط مباشر أو عن طريق بعض الخيارات في الطلب من نوعية "أخذ" (GET Request)، واجهت هذه المشكلة عند استخراج البيانات من موقع بوابة الشعراء.

الحل المقترح:
بدلا من أن يعيد المعالج رابط الصفحة، يعيد الصفحة نفسها ككائن (object) من نوع رد response.
ما رأيك @AliOsm ؟

**Comment by AliOsm** [comment]
بناءً على اجتماعنا، قررنا تحسين الشفرة البرمجية التأسيسية من خلال إضافة نوع ثالث وهو `FormRequestOptions` للقيمة التي يمكن إرجاعها من الدالة `process` في معالجات العصر والشاعر كقيمة للصفحة التالية التي يجب معالجتها. باستخدام هذا النوع الجديد، يمكننا تحديد نوع الطلب الذي يجب القيام به سواءً كان `Request` مع رابط مباشر أو `Selector`، أو `FormRequest` مع `FormRequestOptions`.

**Comment by MagedSaeed** [comment]
خلال العمل على سحب بيانات الموقع، تبين أن هذا غير داع، وأن هناك بعض الطرفيات APIs التي يمكن الاستفادة منها، كما تم تبيين هذا في طلب الأخذ #3
