### ISSUE TITLE
إضافة حالة اختبار شاملة للتأكد من أن الشفرة البرمجية التأسيسية تعمل بشكل جيّد بعد التعديل

### ISSUE THREAD

**Issue by AliOsm** [ARBML/tnqeeb#52]
واجهنا الكثير من المشاكل عند التعديل على الشفرة البرمجية التأسيسية بسبب عدم وجود حالات اختبار تتأكد من صحتها. يجب إضافة حالات اختبار تقوم بتشغيل جامع بيانات فعليًّا.

**Comment by MagedSaeed** [comment]
كيف ستتم هذه؟

**Comment by AliOsm** [comment]
لدي فكرة لكن من الصعب شرحها حاليا. أحتاج أن أنتهي من https://github.com/ARBML/tnqeeb/issues/53 في البداية.

**Comment by AliOsm** [comment]
سأبدا العمل على هذه المشكلة لكي نستطيع التطوير والتحسين بأريحية أكبر.
