### ISSUE TITLE
استيراد العناصر والمعالجات من مكتبة داخلية لتصغير سطور الاستيراد

### ISSUE THREAD

**Issue by MagedSaeed** [ARBML/tnqeeb#59]
بعد مراجعة طلب الأخذ https://github.com/ARBML/tnqeeb/pull/55، أظن أنا بحاجة إلى هذا التعديل لتصغير سطور الاستيراد، ما رأيكم @AliOsm @zaidalyafeai ؟

**Comment by AliOsm** [comment]
ممكن توضيح أكثر؟

**Comment by MagedSaeed** [comment]
مثلا 
```
from poetry.src.websites.adabworld.items.adabworld_era_item import AdabWorldEraItem
```
تصير
```
from poetry.src.websites.adabworld.items import AdabWorldEraItem
```
الشيء ذاته ينطبق على المعالجات وربما site_settings

**Comment by AliOsm** [comment]
نعم إذا كان بالإمكان فعل ذلك فسيكون ممتاز.

**Comment by MagedSaeed** [comment]
حسنا
انتظر انتهاء الفرع الخاص ب @zaidalyafeai واعمل على هذه بعد ذلك.
